[package]
name = "search_engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
tantivy = "0.24"

walkdir = "2.3"
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"